apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: readarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
