apiVersion: batch/v1
kind: CronJob
metadata:
  name: prowlarr-backup
  namespace: prowlarr
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "Backup job needs write access to create tar archives"
    ignore-check.kube-linter.io/run-as-non-root: "Backup job needs root to read all files"
    ignore-check.kube-linter.io/unset-cpu-requirements: "Backup job runs infrequently and doesn't need CPU limits"
    ignore-check.kube-linter.io/unset-memory-requirements: "Backup job memory usage varies with backup size"
spec:
  schedule: "0 3 * * *"  # Daily at 3am
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: alpine:3.19
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache tar gzip
                  BACKUP_DIR="/backup"
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  BACKUP_FILE="$BACKUP_DIR/prowlarr-$TIMESTAMP.tar.gz"
                  
                  mkdir -p "$BACKUP_DIR"
                  tar -czf "$BACKUP_FILE" -C /config .
                  
                  # Keep only last 7 days of backups
                  find "$BACKUP_DIR" -name "prowlarr-*.tar.gz" -mtime +7 -delete
                  
                  # Create a 'latest' symlink
                  ln -sf "$BACKUP_FILE" "$BACKUP_DIR/latest.tar.gz"
                  
                  echo "Backup completed: $BACKUP_FILE"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: backup
                  mountPath: /backup
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: prowlarr-config
            - name: backup
              hostPath:
                path: /mnt/storage/backups/prowlarr
                type: DirectoryOrCreate
