apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  values:
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.home.local
              paths:
                - path: /
                  pathType: Prefix
            - host: immich.${DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
