apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: '>=0.7.0 <1.0.0'
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  values:
    env:
      TZ: Asia/Manila
    
    image:
      tag: v1.122.3  # Pin to specific version
    
    immich:
      persistence:
        library:
          existingClaim: immich-library
    
    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              env:
                DB_HOSTNAME: postgres.immich.svc.cluster.local
                DB_USERNAME: immich
                DB_DATABASE_NAME: immich
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: immich-db
                      key: password
      persistence:
        nextcloud-photos:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: nextcloud-photos-readonly
          globalMounts:
            - path: /nextcloud
              readOnly: true
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.home.local
              paths:
                - path: /
                  pathType: Prefix
    
    # Using external PostgreSQL with pgvector (tensorchord/pgvecto-rs:pg14)
    # Using Valkey instead of Redis (chart v0.10.0+ requirement)
    valkey:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
    
    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: emptyDir
