apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: '>=0.7.0 <1.0.0'
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 12h
  values:
    env:
      TZ: Asia/Manila
      DB_HOSTNAME: postgres.immich.svc.cluster.local
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db
            key: password
    
    image:
      tag: v1.122.3  # Pin to specific version
    
    immich:
      persistence:
        library:
          existingClaim: immich-library
    
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.home.local
              paths:
                - path: /
                  pathType: Prefix
    
    # Use external PostgreSQL with pgvector
    postgresql:
      enabled: false
    
    # Use Valkey instead of Redis
    redis:
      enabled: false
    
    valkey:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
    
    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: emptyDir
